
tasks:
    - name: Install dependencies
      command: |
        export PIP_USER=false
        make install
    - name: Generate config
      command: |
        eval $(gp env -e)
        pip3 install yq
        echo "$EMBEDBASE_CONFIG" | yq -y > config.yaml
    - name: Authenticate to Google Cloud
      command: |
        eval $(gp env -e)
        gcloud auth login
        gcloud config set project embedbase
        echo "sat project to embedbase"
        mkdir -p ~/.docker
        cat >~/.docker/config.json <<EOL
        {
          "credHelpers": {
            "gcr.io": "gcloud",
            "us.gcr.io": "gcloud",
            "eu.gcr.io": "gcloud",
            "asia.gcr.io": "gcloud",
            "staging-k8s.gcr.io": "gcloud",
            "marketplace.gcr.io": "gcloud"
          }
        }
        EOL
    - name: Init Supabase
      command: |
        npx supabase

# TODO: gcloud install
image: # TODO:broken image?
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - github.copilot
    - toba.vsfire
    - wix.vscode-import-cost
    - aaron-bond.better-comments
    - perkovec.emoji
    - ms-python.vscode-pylance
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter
    - k--kato.intellij-idea-keybindings
    - trungngo.autoflake
    - christian-kohler.npm-intellisense
    - dbaeumer.vscode-eslint


ports:
  - port: 8000
    visibility: public