version: '3.7'

services:
  embedbase:
    container_name: embedbase-hosted
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn embedbase.api:app --reload --log-level debug --host 0.0.0.0
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./middlewares/endpoint/endpoint.py:/app/middlewares/endpoint.py
