version: '3.7'

services:
  embedbase:
    container_name: embedbase-hosted
    image: gcr.io/obsidian-ai/embedbase-hosted:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./middlewares/endpoint/endpoint.py:/app/middlewares/endpoint.py
