apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: embedbase-hosted-dev
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "20"
    spec:
      serviceAccountName: embedbase-cloud-run@embedbase.iam.gserviceaccount.com
      containerConcurrency: 80
      containers:
        image: gcr.io/embedbase/embedbase-hosted:0.0.1
        # TODO: fix health?
        # startupProbe:
        #   httpGet:
        #     path: /health
        #   initialDelaySeconds: 30
        #   successThreshold: 1
        #   periodSeconds: 30
        #   timeoutSeconds: 30
        #   failureThreshold: 30
        env:
          - name: ENVIRONMENT
            value: "development"
          - name: UPLOAD_BATCH_SIZE
            value: "100"
          - name: MAX_NOTE_LENGTH
            value: "2000"
        ports:
          - containerPort: 8080
            name: http1
        resources:
          limits:
            cpu: "2"
            memory: 2048Mi
        volumeMounts:
          - name: settings
            readOnly: true
            mountPath: /secrets
      volumes:
        - name: settings
          secret:
            secretName: EMBEDBASE_HOSTED
            items:
              - key: "1"
                path: config.yaml
      timeoutSeconds: 120